---

- name: create config directory
  file: 
    path={{ foreman_hammer_cli_config_path }}
    owner={{ foreman_hammer_cli_config_owner }}
    group={{ foreman_hammer_cli_config_group }}
    mode=0750
    state=directory

- name: render config file for foreman plugin
  template: 
    src=foreman.yml.j2
    dest={{ foreman_hammer_cli_config_path }}/{{ foreman_hammer_cli_foreman_config }}
    owner={{ foreman_hammer_cli_config_owner }}
    group={{ foreman_hammer_cli_config_group }}
    mode={{ foreman_hammer_cli_config_mode }}
  tags:
    - foreman-proxy
    - foreman-proxy-settings
