---

- name: create config directory
  file: 
    path={{ foreman_hammer_cli_config_path }}
    owner={{ foreman_hammer_cli_config_owner }}
    group={{ foreman_hammer_cli_config_group }}
    mode=0750
    state=directory
  tags:
    - foreman-hammer_cli

- name: render foreman config
  template:
    src=foreman.yml.j2
    dest={{ foreman_hammer_cli_config_path }}/foreman{{ foreman_hammer_cli_config_path_suffix }}.yml
    owner={{ foreman_hammer_cli_config_owner }}
    group={{ foreman_hammer_cli_config_group }}
    mode={{ foreman_hammer_cli_config_mode }}
  tags:
    - foreman-hammer_cli

- name: render config file for foreman plugin
  template: 
    src={{ item }}.yml.j2
    dest={{ foreman_hammer_cli_config_path }}/{{ item }}.yml
    owner={{ foreman_hammer_cli_config_owner }}
    group={{ foreman_hammer_cli_config_group }}
    mode={{ foreman_hammer_cli_config_mode }}
  with_items: foreman_hammer_cli_plugins
  tags:
    - foreman-hammer_cli

