---

- name: install foreman-hammer_cli
  package:
    name: rubygem-hammer_cli
    state: present

- name: manage plugins OS agnostic
  package:
    name: "{{ foreman_hammer_cli_plugin_prefix }}{{ item }}"
    state: "{{ foreman_hammer_cli_plugins_state }}"
  with_items: foreman_hammer_cli_plugins
  tags:
    - foreman-hammer-cli-plugins-install
