---
# tasks file for kostyrevaa.foreman-hammer_cli

- name: Set OS dependent variables
  include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
   - "{{ ansible_distribution }}.yml"
   - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
   - "{{ ansible_os_family }}.yml"
   - default.yml
  tags:
    - foreman-hammer_cli
    - always

- include: install.yml
  when: ansible_os_family == "RedHat" or ansible_os_family == "Centos"

- include: configure.yml
